name: PlatformIO CI (Supermini)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - uses: actions/checkout@v4

      - name: Clone nicenano-example
        run: git clone https://github.com/bertrik/nicenano-example

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Supermini
        run: |
          cd nicenano-example/supermini
          pio run

      - name: Convert HEX to UF2
        run: |
          wget https://raw.githubusercontent.com/microsoft/uf2/master/utils/uf2conv.py
          wget https://raw.githubusercontent.com/microsoft/uf2/master/utils/uf2families.json
          # -i: input file .hex
          # -c: convert to UF2
          # -f: Family ID (for nRF52840 use 0xADA52840)
          # -o: output file .uf2
          python3 uf2conv.py \
            -i nicenano-example/supermini/.pio/build/supermini/firmware.hex \
            -c -f 0xADA52840 \
            -o nicenano-example/supermini/.pio/build/supermini/firmware.uf2

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: supermini-firmware
          path: |
            nicenano-example/supermini/.pio/build/supermini/firmware.zip
            nicenano-example/supermini/.pio/build/supermini/firmware.uf2