name: PlatformIO CI (Supermini)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone nicenano-example
        run: git clone https://github.com/bertrik/nicenano-example

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Supermini
        run: |
          cd nicenano-example/supermini
          pio run

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: master-firmware  
          path: nicenano-example/supermini/.pio/build/supermini/firmware.zip 